import Layout from "@/components/Layout";

export default function Privacy() {
  return (
    <Layout>
      <div className="pt-28 pb-14 px-6 max-w-3xl mx-auto">
        <h1 className="text-4xl font-bold mb-6">Privacy Policy</h1>
        
        <div className="prose prose-slate max-w-none text-muted-foreground space-y-6">
          <p>Last updated: October 2025</p>

          <h2 className="text-2xl font-semibold text-foreground mt-6 mb-3">1. Information We Collect</h2>
          <p>
            CoSell ("we," "our," or "us") provides AI-powered sales intelligence software. We collect information you provide directly to us, such as when you create or modify your account, request support, or otherwise communicate with us.
          </p>

          <h2 className="text-2xl font-semibold text-foreground mt-6 mb-3">2. How We Use Your Information</h2>
          <p>
            We use the information we collect to provide, maintain, and improve our services, including to process transactions, send related information, and respond to your comments and questions. We use data provided by our users to inform the insights generated by our AI agents.
          </p>

          <h2 className="text-2xl font-semibold text-foreground mt-6 mb-3">3. Data Security</h2>
          <p>
            We take reasonable measures to help protect information about you from loss, theft, misuse and unauthorized access, disclosure, alteration and destruction.
          </p>

          <h2 className="text-2xl font-semibold text-foreground mt-6 mb-3">4. Cookies</h2>
          <p>
            We use cookies and similar tracking technologies to track the activity on our service and hold certain information to improve and analyze our service.
          </p>

          <h2 className="text-2xl font-semibold text-foreground mt-6 mb-3">5. Contact Us</h2>
          <p>
            If you have any questions about this Privacy Policy, please contact us at pranav@trycosell.com.
          </p>
        </div>
      </div>
    </Layout>
  );
}
